language: node_js
cache: yarn

node_js:
  - 14
  - 12
  - 10

script: yarn test && (yarn coveralls || true)

jobs:
  include:
    - stage: deploy
      name: 'Deploy packages'
      node_js: 12
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: yarn release && yarn docs:publish

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
